name: First Workflow
# manually start the workflow 
on: workflow_dispatch  
jobs:
  first-job:
    runs-on: ununtu-latest
    steps: 
      - name: Print greeting
        run: echo "Hellp World!"
      - name: Print goodbye
        run: echo "Done Bye!"
